//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceTB
    {
        public int Attendance_id { get; set; }
        public int Student_id { get; set; }
        public int Course_id { get; set; }
        public string Attendance_status { get; set; }
        public System.DateTime Attendance_date { get; set; }
    
        public virtual CourseTB CourseTB { get; set; }
        public virtual StudentTB StudentTB { get; set; }
    }
}
