//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSDBEntities : DbContext
    {
        public CMSDBEntities()
            : base("name=CMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminTB> AdminTBs { get; set; }
        public DbSet<AttendanceTB> AttendanceTBs { get; set; }
        public DbSet<ClassTB> ClassTBs { get; set; }
        public DbSet<CourseTB> CourseTBs { get; set; }
        public DbSet<ExamTB> ExamTBs { get; set; }
        public DbSet<FeesdetailsTB> FeesdetailsTBs { get; set; }
        public DbSet<GradeTB> GradeTBs { get; set; }
        public DbSet<MarksTB> MarksTBs { get; set; }
        public DbSet<NoticeTB> NoticeTBs { get; set; }
        public DbSet<PaymentTB> PaymentTBs { get; set; }
        public DbSet<StudentTB> StudentTBs { get; set; }
        public DbSet<SubjectTB> SubjectTBs { get; set; }
        public DbSet<TeacherTB> TeacherTBs { get; set; }
    }
}
