//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTB
    {
        public ExamTB()
        {
            this.MarksTBs = new HashSet<MarksTB>();
        }
    
        public int Exam_id { get; set; }
        public int Course_id { get; set; }
        public int Subject_id { get; set; }
        public System.DateTime Exam_date { get; set; }
        public string Exam_comment { get; set; }
    
        public virtual CourseTB CourseTB { get; set; }
        public virtual SubjectTB SubjectTB { get; set; }
        public virtual ICollection<MarksTB> MarksTBs { get; set; }
    }
}
