//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarksTB
    {
        public int Marks_id { get; set; }
        public int Student_id { get; set; }
        public int Subject_id { get; set; }
        public int Exam_id { get; set; }
        public int Total_marks { get; set; }
        public int Obtained_marks { get; set; }
        public string Attendance_status { get; set; }
    
        public virtual ExamTB ExamTB { get; set; }
        public virtual StudentTB StudentTB { get; set; }
        public virtual SubjectTB SubjectTB { get; set; }
    }
}
