//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTB
    {
        public StudentTB()
        {
            this.AttendanceTBs = new HashSet<AttendanceTB>();
            this.FeesdetailsTBs = new HashSet<FeesdetailsTB>();
            this.MarksTBs = new HashSet<MarksTB>();
            this.PaymentTBs = new HashSet<PaymentTB>();
        }
    
        public int Student_id { get; set; }
        public int Course_id { get; set; }
        public int Class_id { get; set; }
        public string Student_surname { get; set; }
        public string Student_name { get; set; }
        public string Student_fathername { get; set; }
        public System.DateTime Student_birthdate { get; set; }
        public string Student_email { get; set; }
        public string Student_mobile { get; set; }
        public System.DateTime Student_joiningdate { get; set; }
        public string Student_gender { get; set; }
        public string Student_address { get; set; }
    
        public virtual ICollection<AttendanceTB> AttendanceTBs { get; set; }
        public virtual ClassTB ClassTB { get; set; }
        public virtual CourseTB CourseTB { get; set; }
        public virtual ICollection<FeesdetailsTB> FeesdetailsTBs { get; set; }
        public virtual ICollection<MarksTB> MarksTBs { get; set; }
        public virtual ICollection<PaymentTB> PaymentTBs { get; set; }
    }
}
