//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTB
    {
        public SubjectTB()
        {
            this.ExamTBs = new HashSet<ExamTB>();
            this.MarksTBs = new HashSet<MarksTB>();
            this.TeacherTBs = new HashSet<TeacherTB>();
        }
    
        public int Subject_id { get; set; }
        public int Course_id { get; set; }
        public string Subject_name { get; set; }
    
        public virtual CourseTB CourseTB { get; set; }
        public virtual ICollection<ExamTB> ExamTBs { get; set; }
        public virtual ICollection<MarksTB> MarksTBs { get; set; }
        public virtual ICollection<TeacherTB> TeacherTBs { get; set; }
    }
}
