//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherTB
    {
        public int Teacher_id { get; set; }
        public int Subject_id { get; set; }
        public string Teacher_name { get; set; }
        public string Teacher_email { get; set; }
        public string Teacher_mobile { get; set; }
        public string Teacher_gender { get; set; }
        public System.DateTime Teacher_birthdate { get; set; }
        public System.DateTime Teacher_joiningdate { get; set; }
        public string Teacher_address { get; set; }
    
        public virtual SubjectTB SubjectTB { get; set; }
    }
}
